### ISSUE TITLE
Better sub-tasks

### ISSUE THREAD

**Issue by xuwenyihust** [xuwenyihust/everyday-action#21]
- [x] Something to display when no sub-tasks
- [x] Turn grey after done
- [x] Allow editing existing sub-tasks
- [x] Allow creating new subtasks
- [x] Allow deleting subtasks
